server.port=8084
spring.application.name=payment-service

spring.kafka.bootstrap-servers=localhost:9092

stripe.api.key=sk_test_your_stripe_secret_key_here

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
